export const strings = {
  selectDoctorText: 'Select Doctor',
  selectDateText: 'Select Date',
  selectTimeText: 'Select Time',
  reasonForVisit: 'Reason for visit',
  confirmAppointmentText: 'Confirm Appointment',
  // Keep the rest unchanged
  medkit: 'MedKit',
  tollFree: '1800-123-4567',
  searchPlaceholder: 'Search doctors, appointments...',
  checkDoctorAvailability: 'Check Doctor\nAvailability',
  bookAppointment: 'Book\nAppointment',
  searchMedicine: 'Search\nMedicine',
  videoConference: 'Video\nConference',
  upcomingAppointments: 'Upcoming appointments',
  viewAll: 'View all',
  generalCheckup: 'General check-up',
  cardiologistCheckup: 'Cardiologist check-up',
  doctorAvailability: 'Doctor Availability',
  available: 'Available',
  busy: 'Busy',
  offline: 'Offline',
  bookNow: 'Book Now',
  searchMedicines: 'Search medicines...',
  nearbyPharmacies: 'Nearby Pharmacies',
  addToCart: 'Add',
  emergencyCall: 'Emergency Video Call',
  nextAvailable: 'Next available in:',
  approved: 'Approved',
  notApproved: 'Not Approved',
  uploadFile: 'Upload File',
  noRecords: 'No records found',
  changeLanguage: 'Change Language',
  updatePhone: 'Update Phone Number',
  healthConditions: 'Health Conditions',
  save: 'Save',
  cancel: 'Cancel',
  submit: 'Submit',
  loading: 'Loading...',
};
